dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide3 password 'decide3'"
  - psql -U postgres -c "create database test_decide owner decide3"
  - psql -U postgres -c "ALTER USER decide3 CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - cd decide
  - python3 manage.py test mixnet
